Avoid crashing due to "Connection reset by peer" on SSL connection error
Traceback (most recent call last):
  File "/opt/miniircd/bin/miniircd", line 797, in start
  File "/opt/miniircd/bin/miniircd", line 846, in loop
  File "/usr/lib/python2.7/ssl.py", line 891, in wrap_socket
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
error: [Errno 104] Connection reset by peer